apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../single-gpu]
configMapGenerator:
  - name: sglang-profile
    behavior: merge
    literals:
      - MODEL_PATH=/models/Qwen3.8-27B-FP8/017b9c7af6b5689d5dd426a76e0bc077eb5ca20a
      - MODEL_REPOSITORY=Qwen/Qwen3.8-27B-FP8
      - MODEL_REVISION=017b9c7af6b5689d5dd426a76e0bc077eb5ca20a
      - SERVED_MODEL_NAME=Qwen3.8-27B-FP8
      - TENSOR_PARALLEL=2
      - CONTEXT_LENGTH=32768
patches:
  - path: sglang.yaml
