apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [deployment.yaml, service.yaml, pvc.yaml]
configMapGenerator:
  - name: sunshine-profile
    literals:
      - SUNSHINE_ENCODER=vulkan
      - SUNSHINE_CAPTURE=kwin
      - SUNSHINE_OUTPUT_NAME=
      - SUNSHINE_HEVC_MODE=0
      - SUNSHINE_AV1_MODE=0
      - SUNSHINE_VK_TUNE=2
      - SUNSHINE_VAAPI_STRICT_RC_BUFFER=disabled
      - GAMING_WIDTH=1920
      - GAMING_HEIGHT=1080
      - GAMING_REFRESH_HZ=60
